-- BobleLoot_Data_sample.lua
-- Fixture for tools/tests/test_scoring.py
-- Generated by hand to exercise all scoring code paths.
-- DO NOT edit without updating the corresponding Python assertions.

BobleLoot_Data = {
    generatedAt = 1745000000,
    simCap      = 5.0,
    mplusCap    = 160,
    historyCap  = 6,

    scoreOverrides = {
        [999001] = 95.0,
    },

    characters = {
        -- Full data: all components present.
        ["Fullchar-Stormrage"] = {
            attendance    = 90.0,
            mplusDungeons = 80,
            mainspec      = "Holy",
            role          = "raider",
            bis      = { [212401] = true },
            sims     = { [212401] = 3.5 },
            simsKnown = { [212401] = true },
            itemsReceived = 2,
        },
        -- Nil-sim path: simsKnown is absent for this item (never simmed).
        ["Nosim-Stormrage"] = {
            attendance    = 75.0,
            mplusDungeons = 40,
            role          = "raider",
            itemsReceived = 1,
        },
        -- Zero-sim path (Batch 1B fix): simsKnown present, sims value 0.0.
        -- Must NOT be treated as nil-sim.
        ["Zerosim-Stormrage"] = {
            attendance    = 80.0,
            mplusDungeons = 60,
            role          = "raider",
            bis      = { [212401] = true },
            sims     = {},
            simsKnown = { [212401] = true },
            itemsReceived = 0,
        },
        -- All-nil-component path: missing attendance AND mplus AND history.
        -- Score:Compute should return nil (no computable score).
        ["Allnil-Stormrage"] = {
            role = "raider",
        },
        -- Trial role: history component should be multiplied by 0.5.
        ["Trialchar-Stormrage"] = {
            attendance    = 60.0,
            mplusDungeons = 20,
            role          = "trial",
            itemsReceived = 0,
        },
        -- Zero history cap: denominator is softFloor (6); itemsReceived=0 -> 1.0.
        ["Noloot-Stormrage"] = {
            attendance    = 100.0,
            mplusDungeons = 160,
            role          = "raider",
            itemsReceived = 0,
        },
    },
}
