#!/usr/bin/env python3
"""wowaudit.py — produce the Lua data file consumed by the Boble Loot addon.

Two modes, auto-selected:

  API fetch (default):
      py tools/wowaudit.py [--api-key ...]

      Pulls the team roster live from https://wowaudit.com. The API key
      can come from --api-key, the WOWAUDIT_API_KEY env var, or a `.env`
      file at the repo root (see .env.example).

  Manual convert:
      py tools/wowaudit.py --wowaudit path/to/export.csv --bis bis.json

      Reads a CSV / XLSX export from wowaudit's "Character data" sheet
      (required columns: character, mplus_dungeons, attendance,
      items_received, plus per-item sim_<itemID> columns) plus a JSON
      file mapping "Name-Realm" -> [BiS itemIDs].

In both modes the output is written to ``../Data/BobleLoot_Data.lua``
relative to this script (i.e. the addon's own Data folder), unless
``--out`` is given.
"""
from __future__ import annotations

import argparse
import csv
import datetime as dt
import json
import os
import sys
import urllib.error
import urllib.request
from pathlib import Path

# --------------------------------------------------------------------------
# .env loader (zero-dependency)
# --------------------------------------------------------------------------

def _load_dotenv() -> None:
    """Load KEY=VALUE pairs from the nearest ``.env`` into os.environ
    without overwriting existing variables."""
    for d in (Path(__file__).resolve().parent, *Path(__file__).resolve().parents):
        candidate = d / ".env"
        if not candidate.is_file():
            continue
        try:
            text = candidate.read_text(encoding="utf-8")
        except OSError:
            return
        for raw in text.splitlines():
            line = raw.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            key, _, value = line.partition("=")
            key = key.strip()
            value = value.strip().strip('"').strip("'")
            if key and key not in os.environ:
                os.environ[key] = value
        return


_load_dotenv()

# --------------------------------------------------------------------------
# constants
# --------------------------------------------------------------------------

DEFAULT_OUT = Path(__file__).resolve().parent.parent / "Data" / "BobleLoot_Data.lua"
REQUIRED_COLS = {"character", "mplus_dungeons", "attendance"}

API_BASE = "https://wowaudit.com/v1"

# --------------------------------------------------------------------------
# CSV / XLSX reading
# --------------------------------------------------------------------------

def _read_table(path: Path) -> list[dict]:
    suffix = path.suffix.lower()
    if suffix in {".xlsx", ".xls"}:
        try:
            from openpyxl import load_workbook  # type: ignore
        except ImportError:
            sys.exit("openpyxl is required to read XLSX inputs (pip install openpyxl)")
        wb = load_workbook(path, data_only=True, read_only=True)
        ws = wb.active
        rows = list(ws.iter_rows(values_only=True))
        if not rows:
            return []
        header = [str(h).strip() if h is not None else "" for h in rows[0]]
        return [
            {header[i]: row[i] for i in range(len(header)) if header[i]}
            for row in rows[1:]
            if any(c is not None for c in row)
        ]
    with path.open(newline="", encoding="utf-8-sig") as f:
        return list(csv.DictReader(f))


def _to_float(v, default=0.0) -> float:
    if v is None or v == "":
        return default
    try:
        return float(str(v).replace("%", "").replace(",", ""))
    except ValueError:
        return default


def _to_int(v, default=0) -> int:
    return int(round(_to_float(v, default)))


def _lua_escape(s: str) -> str:
    return s.replace("\\", "\\\\").replace('"', '\\"')

# --------------------------------------------------------------------------
# Lua emitter
# --------------------------------------------------------------------------

def build_lua(
    rows: list[dict],
    bis: dict[str, list[int]],
    sim_cap: float,
    mplus_cap: int,
    history_cap: int,
    team_url: str | None = None,
) -> str:
    if not rows:
        sys.exit("No rows to emit.")

    missing = REQUIRED_COLS - set(rows[0].keys())
    if missing:
        sys.exit(f"Input is missing required columns: {sorted(missing)}")

    sim_cols_set = set()
    for r in rows:
        for c in r.keys():
            if c.startswith("sim_") and c[4:].isdigit():
                sim_cols_set.add(c)
    sim_cols = sorted(sim_cols_set, key=lambda c: int(c[4:]))

    now_iso = dt.datetime.now(dt.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    out = []
    out.append("-- AUTO-GENERATED by tools/wowaudit.py - do not edit by hand.")
    out.append(f"-- Generated: {now_iso}")
    out.append("BobleLoot_Data = {")
    out.append(f'    generatedAt = "{now_iso}",')
    if team_url:
        out.append(f'    teamUrl     = "{team_url}",')
    out.append(f"    simCap      = {sim_cap},")
    out.append(f"    mplusCap    = {mplus_cap},")
    out.append(f"    historyCap  = {history_cap},")
    out.append("    characters  = {")

    for row in rows:
        name = (row.get("character") or "").strip()
        if not name:
            continue
        attendance = _to_float(row.get("attendance"))
        mplus      = _to_int(row.get("mplus_dungeons"))

        out.append(f'        ["{_lua_escape(name)}"] = {{')
        out.append(f"            attendance    = {attendance},")
        out.append(f"            mplusDungeons = {mplus},")

        bis_ids = bis.get(name) or []
        if bis_ids:
            ids = ", ".join(f"[{int(i)}] = true" for i in bis_ids)
            out.append(f"            bis  = {{ {ids} }},")
        else:
            out.append("            bis  = {},")

        sim_pairs = []
        for col in sim_cols:
            val = _to_float(row.get(col), default=None) if row.get(col) not in (None, "") else None
            if val is None:
                continue
            item_id = int(col[4:])
            sim_pairs.append(f"[{item_id}] = {val}")
        if sim_pairs:
            out.append(f"            sims = {{ {', '.join(sim_pairs)} }},")
        else:
            out.append("            sims = {},")

        out.append("        },")

    out.append("    },")
    out.append("}")
    out.append("")
    return "\n".join(out)

# --------------------------------------------------------------------------
# API fetch
# --------------------------------------------------------------------------

def http_get_json(path: str, api_key: str) -> object:
    url = API_BASE + path
    req = urllib.request.Request(
        url,
        headers={
            "Authorization": api_key,
            "Accept":        "application/json",
            "User-Agent":    "BobleLoot/0.1 (+wowaudit.py)",
        },
    )
    try:
        with urllib.request.urlopen(req, timeout=30) as r:
            return json.load(r)
    except urllib.error.HTTPError as e:
        body = e.read().decode("utf-8", errors="replace")[:500]
        sys.exit(f"HTTP {e.code} from {url}: {body}")
    except urllib.error.URLError as e:
        sys.exit(f"Network error contacting {url}: {e.reason}")


def _full_name(name: str | None, realm: str | None) -> str | None:
    if not name:
        return None
    if realm:
        # Strip spaces from realm to match WoW's "Name-Realm" format.
        realm_clean = "".join(realm.split())
        return f"{name}-{realm_clean}"
    return name


def _best_wishlist_score(item: dict) -> float:
    """Pick the highest sim percentage across all specs/wishes for an item.

    wowaudit's API returns `score_by_spec[spec].percentage` and
    `wishes[*].percentage` as percent values already (e.g. 2.9 means a
    2.9% upgrade, 0.0744 means a 0.0744% sidegrade). We pass them
    through unchanged.
    """
    best = 0.0
    sbs = item.get("score_by_spec")
    if isinstance(sbs, dict):
        for spec_data in sbs.values():
            if isinstance(spec_data, dict):
                p = spec_data.get("percentage")
                if isinstance(p, (int, float)) and p > best:
                    best = p
    for w in item.get("wishes") or []:
        if isinstance(w, dict):
            p = w.get("percentage")
            if isinstance(p, (int, float)) and p > best:
                best = p
    return float(best)


def fetch_rows(api_key: str, dump_dir: Path | None) -> list[dict]:
    """Hit all the wowaudit endpoints we need and merge them into rows
    matching the convert-mode CSV schema (one dict per character)."""

    def fetch(path: str, label: str) -> object:
        data = http_get_json(path, api_key)
        if dump_dir is not None:
            dump_dir.mkdir(parents=True, exist_ok=True)
            (dump_dir / f"{label}.json").write_text(
                json.dumps(data, indent=2), encoding="utf-8")
        return data

    period_info = fetch("/period", "period")
    season      = (period_info or {}).get("current_season") or {}
    first_pid   = season.get("first_period_id")
    cur_pid     = (period_info or {}).get("current_period")
    season_start = season.get("start_date")  # ISO date string, e.g. "2026-03-17"

    roster      = fetch("/characters", "characters")
    if not isinstance(roster, list):
        sys.exit(f"Unexpected /characters shape: {type(roster).__name__}")

    # Scope attendance to the current season so a long-tenured raider's
    # lifetime number doesn't mask recent absences.
    att_path = "/attendance"
    if season_start:
        att_path += f"?start_date={season_start}"
    attendance_payload = fetch(att_path, "attendance")
    att_chars = attendance_payload.get("characters", []) if isinstance(attendance_payload, dict) else []
    attendance_by_id = {
        c["id"]: c.get("attended_percentage", 0)
        for c in att_chars if isinstance(c, dict) and "id" in c
    }

    # Sum M+ dungeons across the whole season, and compute weeks elapsed
    # so we can scale the M+ cap with the season's progression.
    dungeons_by_id: dict[int, int] = {}
    weeks_in_season = 0
    if isinstance(first_pid, int) and isinstance(cur_pid, int) and first_pid <= cur_pid:
        weeks_in_season = cur_pid - first_pid + 1
        for pid in range(first_pid, cur_pid + 1):
            payload = fetch(f"/historical_data?period={pid}", f"historical_{pid}")
            for c in (payload or {}).get("characters", []) if isinstance(payload, dict) else []:
                cid = c.get("id")
                done = (c.get("data") or {}).get("dungeons_done") or []
                if isinstance(cid, int) and isinstance(done, list):
                    dungeons_by_id[cid] = dungeons_by_id.get(cid, 0) + len(done)

    wl_payload = fetch("/wishlists", "wishlists")
    wl_chars   = wl_payload.get("characters", []) if isinstance(wl_payload, dict) else []
    sims_by_id: dict[int, dict[int, float]] = {}
    for c in wl_chars:
        if not isinstance(c, dict):
            continue
        cid = c.get("id")
        if not isinstance(cid, int):
            continue
        sims_by_id.setdefault(cid, {})
        for inst in c.get("instances") or []:
            for diff in inst.get("difficulties") or []:
                wl = diff.get("wishlist") or {}
                for enc in wl.get("encounters") or []:
                    for item in enc.get("items") or []:
                        iid = item.get("id")
                        if not isinstance(iid, int):
                            continue
                        score = _best_wishlist_score(item)
                        # Keep the best score across encounters/difficulties.
                        prev = sims_by_id[cid].get(iid, 0.0)
                        if score > prev:
                            sims_by_id[cid][iid] = score

    rows: list[dict] = []
    for c in roster:
        if not isinstance(c, dict):
            continue
        cid   = c.get("id")
        full  = _full_name(c.get("name"), c.get("realm"))
        if not full:
            continue
        row = {
            "character":      full,
            "mplus_dungeons": dungeons_by_id.get(cid, 0),
            "attendance":     attendance_by_id.get(cid, 0),
        }
        for iid, score in (sims_by_id.get(cid) or {}).items():
            row[f"sim_{iid}"] = score
        rows.append(row)

    return rows, weeks_in_season


def fetch_team_url(api_key: str) -> str | None:
    try:
        team = http_get_json("/team", api_key)
        if isinstance(team, dict):
            return team.get("url")
    except Exception:
        pass
    return None


# --------------------------------------------------------------------------

def main():
    ap = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    # Mode selection (auto): if --wowaudit is given, convert mode; else API.
    ap.add_argument("--wowaudit", type=Path, default=None,
                    help="CSV/XLSX export. Switches to convert mode (no API call).")
    ap.add_argument("--bis",      type=Path, default=None,
                    help="JSON file: { \"Name-Realm\": [itemID, ...] }. "
                         "Required in convert mode; optional in API mode.")
    # API mode
    ap.add_argument("--api-key", default=os.environ.get("WOWAUDIT_API_KEY"),
                    help="WoWAudit team API key (or WOWAUDIT_API_KEY env var, or .env file).")
    ap.add_argument("--dump-raw", type=Path, default=None,
                    help="Directory to also write raw API responses into (debugging).")
    # Output
    ap.add_argument("--out", type=Path, default=DEFAULT_OUT,
                    help=f"Output .lua path (default: {DEFAULT_OUT}).")
    ap.add_argument("--sim-cap",     type=float, default=5.0)
    ap.add_argument("--mplus-cap",   type=int,   default=None,
                    help="Override M+ dungeons cap. Default: 10 per week of "
                         "the current season (so it grows over the season).")
    ap.add_argument("--mplus-cap-per-week", type=int, default=10,
                    help="Per-week increment for the auto M+ cap (default 10).")
    ap.add_argument("--history-cap", type=int,   default=5)
    args = ap.parse_args()

    weeks_in_season = 1
    team_url = None
    if args.wowaudit is not None:
        # Convert mode.
        if args.bis is None:
            sys.exit("--bis is required when using --wowaudit.")
        rows = _read_table(args.wowaudit)
        with args.bis.open(encoding="utf-8") as f:
            bis_raw = json.load(f)
        bis = {k: [int(x) for x in v] for k, v in bis_raw.items()}
    else:
        # API fetch mode.
        if not args.api_key:
            sys.exit("No API key. Pass --api-key, set WOWAUDIT_API_KEY, "
                     "or put it in a .env file. Alternatively pass --wowaudit "
                     "to convert a manual export.")
        rows, weeks_in_season = fetch_rows(args.api_key, args.dump_raw)
        team_url = fetch_team_url(args.api_key)
        if not rows:
            sys.exit("No characters parsed from the API response.")
        if args.bis is not None:
            with args.bis.open(encoding="utf-8") as f:
                bis_raw = json.load(f)
            bis = {k: [int(x) for x in v] for k, v in bis_raw.items()}
        else:
            # wowaudit's API doesn't expose a BiS flag; supply --bis to populate.
            bis = {}

    if args.mplus_cap is not None:
        mplus_cap = args.mplus_cap
    else:
        mplus_cap = max(args.mplus_cap_per_week,
                        args.mplus_cap_per_week * max(weeks_in_season, 1))

    lua = build_lua(rows, bis, args.sim_cap, mplus_cap, args.history_cap, team_url)
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(lua, encoding="utf-8")
    print(f"Wrote {args.out}: {len(rows)} characters, "
          f"{sum(len(v) for v in bis.values())} BiS entries. "
          f"M+ cap = {mplus_cap} ({weeks_in_season} week(s) into season).")


if __name__ == "__main__":
    main()
